#!/usr/bin/Rscript
message('Starting...')

final <- try({
	root <- file.path(path.expand("~"), "SeqPlots_data")
	suppressPackageStartupMessages(require(BSgenome))
		
	a=2
	while (a!=1) {
		a=system(paste0('CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --text "SeqPlots v', packageVersion('seqplots'), ' (Mac OS X bundle ref: $(./git rev-parse --short=4 @{0}))" --informative-text "', 
		'Currently installed genomes:\n', paste0('-', BSgenome::installed.genomes(), collapse='\n'), '\n------------------------------------------------ \n Data location: ', root, 
		'" --button1 "START" --button2 "Install new genomes/updates" --button3 "Change data location" --title "SeqPlots Setup" --icon info --float'), intern=TRUE)
		if(a==2) {
			a2=system(paste0('CocoaDialog.app/Contents/MacOS/CocoaDialog dropdown --title "Install new genomes or updates" --text "Choose reference genome package..." --items ', 
				paste(suppressMessages(available.genomes()), collapse=' '), ' --button1 "Ok" --button2 "Cancel" --button3 "Install from local file" --string-output'), intern=TRUE)
			if(a2[[1]] == 'Ok') {
				biocLite(a2[[2]], suppressUpdates=TRUE, ask=FALSE)
			} else if(a2[[1]] == 'Install from local file') {
				a3=system('CocoaDialog.app/Contents/MacOS/CocoaDialog fileselect --title "Select reference genome or update package.."', intern=TRUE)
				if(length(a3) > 0) install.packages(a3)
			}
		}
		if(a==3) {
			a3=system('CocoaDialog.app/Contents/MacOS/CocoaDialog fileselect --select-only-directories --title "Select data location..."', intern=TRUE)
			if(length(a3) > 0) root <- a3
		}
	}
	message('Data loaction: ', root)
	message('Loading packages...')
	suppressPackageStartupMessages( library(seqplots) )
	
	seqplots::run( root = root, launch.browser = TRUE )
})

if( class(final) == "try-error" ) {
	if( system(paste0('CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --text "Error occurred. SeqPlots will terminate."', 
		' --informative-text "Please investigate *details* on SeqPlots diagnostic window for more information. Last error message:\n\n',  
		attributes(final)$condition$message, '" --button1 "OK"  --button3 "Report Issue" --title "ERRER" --icon x --float'), 
	intern=TRUE) == 3) {
		browseURL('https://github.com/Przemol/seqplots/issues/new')
	}
}
