#!/bin/sh

#[[ $(which Xorg) ]] && echo 'System check: OK' || (CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --string-output --text "Xorg not found" --informative-text 'Install X11 from http://xquartz.macosforge.org (http://support.apple.com/kb/ht5293)' --button1 "OK" --title "Setup" --icon atom --float > /dev/null && open http://xquartz.macosforge.org);

export GIT_EXEC_PATH='./git-core'

./git fetch --depth=1

LOCAL=$(./git rev-parse @{0})
REMOTE=$(./git rev-parse @{u})
BASE=$(./git merge-base @ @{u})

if [ $LOCAL = $REMOTE ]; then
    echo "App is up-to-date"
    UPDATE=0

elif [ $LOCAL = $BASE ]; then
    UPDATE=$(CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --button1 "NO" --button2 "YES" --float --title "SeqPlots app update avilable" --text "New version available!" --informative-text "Current version [$(./git rev-parse --short=4 $LOCAL)] can be updated to [$(./git rev-parse --short=4 $REMOTE)] Do you want to update?")

elif [ $REMOTE = $BASE ]; then
    echo "App is ahead of repo"
    UPDATE=0

else
    echo "App diverged from repo"
    UPDATE=0

fi

if [ $UPDATE = 2 ]; then
    ./git fetch --depth=1
    ./git reset --hard origin/master
    ./git gc --prune=now
fi


export RHOME=$(pwd)/Rbin/Resources
export R_HOME_DIR=$(pwd)/Rbin/Resources
$RHOME/bin/Rscript init
