#!/usr/bin/Rscript
message('Loading application...')

final <- try({
    CONF <- read.dcf('seqplots.dcf', all = TRUE)
    if(is.null(CONF$root)) {
        root <- file.path(path.expand("~"), "SeqPlots_data")
    } else {
        root <- CONF$root
    }
    
    if( as.logical(CONF$askupdate) ) { try({    	
		txt <- httr::content(httr::GET(
            'https://raw.githubusercontent.com/Przemol/seqplots_osx/master/SeqPlots.app/Contents/Resources/seqplots.dcf'
        ))		
		new <- read.dcf(textConnection(txt), all=TRUE)$version
		if( as.package_version(new) > as.package_version(CONF$version) ) {
		upd <- system(paste0(
            'CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --title "Update Available" ',
		    '--text "SeqPlots OS X boundle version ', new, ' is now available." ',
            '--informative-text "You are using version ', CONF$version, '" ',     	
		    '--button1 "Quit and Download" --button2 "Remind later" --button3 "Ignore updates" --float'), 		
		   intern=TRUE)
			if( upd == 1 ) {
			    browseURL('https://github.com/Przemol/seqplots_osx/releases/latest')
			    quit(save = "no")
			} else if ( upd == 3 ) {
			    CONF$askupdate <- FALSE
			    write.dcf(CONF, 'seqplots.dcf')
			}
		}		
	})}
    
	#set up rooth here
    suppressPackageStartupMessages(require(BSgenome))
    
	if( !file.exists(file.path(root, 'genomes')) ) {
        dir.create(file.path(root, 'genomes'))
	}
	.libPaths(c( .libPaths(), file.path(root, 'genomes') ))
		
	a=2
	while (a!=1) {
		a=system(paste0(
            'CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --text "SeqPlots v',
            packageVersion('seqplots'), 
            ' (Mac OS X bundle version: ',
            CONF$version,
            ')" --informative-text "', 
		    'Currently installed genomes:\n', 
            paste0('-', BSgenome::installed.genomes(), collapse='\n'), 
            '\n------------------------------------------------ \n Data location: ', 
            root, 
		    '" --button1 "START" --button2 "Install new genomes/updates" --button3 "Change data location" --title "SeqPlots Setup" --icon info --float'
        ), intern=TRUE)
		if(a==2) {
			a2=system(paste0('CocoaDialog.app/Contents/MacOS/CocoaDialog dropdown --title "Install new genomes or updates" --text "Choose reference genome package..." --items ', 
				paste(suppressMessages(available.genomes()), collapse=' '), ' --button1 "Ok" --button2 "Cancel" --button3 "Install from local file" --string-output'), intern=TRUE)
			if(a2[[1]] == 'Ok') {
				biocLite(a2[[2]], suppressUpdates=TRUE, ask=FALSE, lib=file.path(root, 'genomes'))
			} else if(a2[[1]] == 'Install from local file') {
				a3=system('CocoaDialog.app/Contents/MacOS/CocoaDialog fileselect --title "Select reference genome or update package.."', intern=TRUE)
				if(length(a3) > 0) install.packages(a3, repos = NULL, lib=file.path(root, 'genomes'), type='source')
			}
		}
		if(a==3) {
			a3=system('CocoaDialog.app/Contents/MacOS/CocoaDialog fileselect --select-only-directories --title "Select data location..."', intern=TRUE)
			if(length(a3) > 0) {
                root <- a3
                CONF$root <- root
                write.dcf(CONF, 'seqplots.dcf')
			}
		}
	}
	#message('Data loaction: ', root)
	#message('Loading packages...')
	suppressPackageStartupMessages( library(seqplots) )
	suppressPackageStartupMessages( library(shiny) )
	
	seqplots::run( root = root, launch.browser = TRUE )
})

if( class(final) == "try-error" ) {
	if( system(paste0('CocoaDialog.app/Contents/MacOS/CocoaDialog msgbox --text "Error occurred. SeqPlots will terminate."', 
		' --informative-text "Please investigate *details* on SeqPlots diagnostic window for more information. Last error message:\n\n',  
		attributes(final)$condition$message, '" --button1 "OK"  --button3 "Report Issue" --title "ERRER" --icon x --float'), 
	intern=TRUE) == 3) {
		browseURL('https://github.com/Przemol/seqplots/issues/new')
	}
}
